import random
import uuid
import re
import httpx
from datetime import datetime, timedelta

from core.database import get_sync_db, sync_engine
from core.config import get_settings
from api.models.models import Base, Skill, Agent

settings = get_settings()


def generate_skill_id(source_url: str, name: str, version: str = "main") -> str:
    """Generate unique skill_id from source_url and name in author/skill-name:version format"""
    match = re.search(r'https?://github\.com/([^/]+)/([^/]+)', source_url)
    if match:
        owner, repo = match.groups()
        skill_slug = name.lower().replace(' ', '-')
        return f"{owner}/{skill_slug}:{version}"
    return f"{name.lower().replace(' ', '-')}:{version}"


def fetch_skill_content(source_url: str, skill_name: str, version: str = "main") -> str | None:
    """Fetch skill.md content from GitHub"""
    match = re.search(r'https?://github\.com/([^/]+)/([^/]+)', source_url)
    if not match:
        return None

    owner, repo = match.groups()
    raw_url = f"https://raw.githubusercontent.com/{owner}/{repo}/{version}/skills/{skill_name}/skill.md"

    headers = {}
    if settings.storage.github_token:
        headers["Authorization"] = f"token {settings.storage.github_token}"

    try:
        response = httpx.get(raw_url, headers=headers, timeout=10.0)
        if response.status_code == 200:
            return response.text
    except Exception:
        pass

    return None


SKILLS_DATA = [
    {"skill_id": "find-skills", "name": "Find Skills", "description": "Search and discover AI agent skills from the skills registry", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/skills", "category": "Search", "tags": ["search", "discovery", "registry"], "platform": "claude", "download_count": 1500000, "rating": "4.9"},
    {"skill_id": "frontend-design", "name": "Frontend Design", "description": "Best practices for building modern frontend applications with React and Next.js", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Development", "tags": ["frontend", "react", "design", "ui"], "platform": "claude", "download_count": 416100, "rating": "4.8"},
    {"skill_id": "vercel-react-best-practices", "name": "Vercel React Best Practices", "description": "Optimized React patterns for Vercel deployment", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/agent-skills", "category": "Development", "tags": ["react", "vercel", "best-practices", "optimization"], "platform": "cursor", "download_count": 401800, "rating": "4.7"},
    {"skill_id": "web-design-guidelines", "name": "Web Design Guidelines", "description": "Comprehensive web design principles and guidelines for building beautiful websites", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/agent-skills", "category": "Design", "tags": ["design", "ui", "ux", "guidelines"], "platform": "claude", "download_count": 321600, "rating": "4.8"},
    {"skill_id": "microsoft-foundry", "name": "Microsoft Foundry", "description": "Azure AI Foundry integration and deployment patterns", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "ai", "foundry", "cloud"], "platform": "claude", "download_count": 321500, "rating": "4.6"},
    {"skill_id": "remotion-best-practices", "name": "Remotion Best Practices", "description": "Create videos programmatically with Remotion and React", "author": "remotion-dev", "source": "github", "source_url": "https://github.com/remotion-dev/skills", "category": "Media", "tags": ["video", "remotion", "animation"], "platform": "cursor", "download_count": 311400, "rating": "4.5"},
    {"skill_id": "azure-messaging", "name": "Azure Messaging", "description": "Azure Service Bus and Event Hubs integration patterns", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "messaging", "service-bus", "events"], "platform": "claude", "download_count": 309000, "rating": "4.5"},
    {"skill_id": "azure-hosted-copilot-sdk", "name": "Azure Hosted Copilot SDK", "description": "Build copilots with Azure AI hosted models", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "AI", "tags": ["azure", "copilot", "ai", "sdk"], "platform": "claude", "download_count": 292400, "rating": "4.7"},
    {"skill_id": "agent-browser", "name": "Agent Browser", "description": "Enable AI agents to browse and interact with web pages", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/agent-browser", "category": "Browser", "tags": ["browser", "automation", "web", "interaction"], "platform": "claude", "download_count": 276100, "rating": "4.6"},
    {"skill_id": "azure-compute", "name": "Azure Compute", "description": "Azure Virtual Machines, App Service, and Container Instances patterns", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "compute", "vm", "containers"], "platform": "claude", "download_count": 263400, "rating": "4.4"},
    {"skill_id": "azure-cloud-migrate", "name": "Azure Cloud Migration", "description": "Strategies and patterns for migrating workloads to Azure", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "migration", "cloud"], "platform": "claude", "download_count": 253600, "rating": "4.5"},
    {"skill_id": "skill-creator", "name": "Skill Creator", "description": "Create new AI agent skills with proper structure and documentation", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Development", "tags": ["skill", "creation", "development"], "platform": "claude", "download_count": 209800, "rating": "4.9"},
    {"skill_id": "azure-cost-optimization", "name": "Azure Cost Optimization", "description": "Reduce Azure spending with cost optimization strategies", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "cost", "optimization", "budget"], "platform": "claude", "download_count": 205500, "rating": "4.6"},
    {"skill_id": "azure-quotas", "name": "Azure Quotas", "description": "Manage and request Azure resource quotas", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "quotas", "limits"], "platform": "claude", "download_count": 190800, "rating": "4.3"},
    {"skill_id": "azure-upgrade", "name": "Azure Upgrade", "description": "Upgrade Azure services and APIs to latest versions", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "upgrade", "migration"], "platform": "claude", "download_count": 183300, "rating": "4.4"},
    {"skill_id": "ai-image-generation", "name": "AI Image Generation", "description": "Generate images using AI models like DALL-E, Stable Diffusion", "author": "inference-sh-skills", "source": "github", "source_url": "https://github.com/inference-sh-skills/skills", "category": "AI", "tags": ["ai", "image", "generation", "dall-e"], "platform": "claude", "download_count": 180800, "rating": "4.7"},
    {"skill_id": "vercel-composition-patterns", "name": "Vercel Composition Patterns", "description": "Advanced composition patterns for React on Vercel", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/agent-skills", "category": "Development", "tags": ["react", "vercel", "patterns"], "platform": "cursor", "download_count": 174800, "rating": "4.6"},
    {"skill_id": "supabase-postgres-best-practices", "name": "Supabase Postgres Best Practices", "description": "PostgreSQL optimization and best practices for Supabase", "author": "supabase", "source": "github", "source_url": "https://github.com/supabase/agent-skills", "category": "Database", "tags": ["supabase", "postgresql", "database", "sql"], "platform": "claude", "download_count": 167900, "rating": "4.8"},
    {"skill_id": "ui-ux-pro-max", "name": "UI/UX Pro Max", "description": "Professional UI/UX design patterns and implementation", "author": "nextlevelbuilder", "source": "github", "source_url": "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill", "category": "Design", "tags": ["ui", "ux", "design", "professional"], "platform": "cursor", "download_count": 166300, "rating": "4.9"},
    {"skill_id": "wonda-cli", "name": "Wonda CLI", "description": "CLI tool for managing AI workflows and prompts", "author": "degausai", "source": "github", "source_url": "https://github.com/degausai/wonda", "category": "Tools", "tags": ["cli", "workflow", "prompts"], "platform": "claude", "download_count": 165500, "rating": "4.5"},
    {"skill_id": "brainstorming", "name": "Brainstorming", "description": "Structured brainstorming techniques for creative problem solving", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Productivity", "tags": ["brainstorming", "creativity", "problem-solving"], "platform": "claude", "download_count": 160300, "rating": "4.7"},
    {"skill_id": "azure-enterprise-infra-planner", "name": "Azure Enterprise Infrastructure Planner", "description": "Plan and design enterprise Azure infrastructure", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "enterprise", "infrastructure", "planning"], "platform": "claude", "download_count": 157400, "rating": "4.5"},
    {"skill_id": "azure-kubernetes", "name": "Azure Kubernetes", "description": "AKS deployment and management patterns", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "kubernetes", "aks", "containers"], "platform": "claude", "download_count": 150300, "rating": "4.6"},
    {"skill_id": "grill-me", "name": "Grill Me", "description": "Interview preparation and practice with AI feedback", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Productivity", "tags": ["interview", "practice", "feedback"], "platform": "claude", "download_count": 147900, "rating": "4.4"},
    {"skill_id": "caveman", "name": "Caveman", "description": "AI-powered code review and improvement suggestions", "author": "juliusbrussee", "source": "github", "source_url": "https://github.com/juliusbrussee/caveman", "category": "Development", "tags": ["code-review", "ai", "improvement"], "platform": "cursor", "download_count": 144200, "rating": "4.5"},
    {"skill_id": "shadcn", "name": "Shadcn UI", "description": "Beautiful and accessible UI components using shadcn/ui", "author": "shadcn", "source": "github", "source_url": "https://github.com/shadcn/ui", "category": "UI Components", "tags": ["ui", "components", "shadcn", "accessibility"], "platform": "cursor", "download_count": 143100, "rating": "4.9"},
    {"skill_id": "github-actions-docs", "name": "GitHub Actions Documentation", "description": "Generate and maintain GitHub Actions workflow documentation", "author": "xixu-me", "source": "github", "source_url": "https://github.com/xixu-me/skills", "category": "DevOps", "tags": ["github", "actions", "ci", "cd", "documentation"], "platform": "claude", "download_count": 138300, "rating": "4.6"},
    {"skill_id": "lark-doc", "name": "Lark Doc", "description": "Lark (Feishu) document operations and management", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "feishu", "document", "office"], "platform": "claude", "download_count": 133500, "rating": "4.4"},
    {"skill_id": "xget", "name": "XGet", "description": "Enhanced file download utility with resume support", "author": "xixu-me", "source": "github", "source_url": "https://github.com/xixu-me/skills", "category": "Tools", "tags": ["download", "file", "utility"], "platform": "cursor", "download_count": 133400, "rating": "4.3"},
    {"skill_id": "tzst", "name": "TZST", "description": "Timezone conversion and handling utilities", "author": "xixu-me", "source": "github", "source_url": "https://github.com/xixu-me/skills", "category": "Tools", "tags": ["timezone", "datetime", "conversion"], "platform": "claude", "download_count": 133400, "rating": "4.2"},
    {"skill_id": "lark-base", "name": "Lark Base", "description": "Lark Base (Bitable) operations and automation", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "base", "database", "automation"], "platform": "claude", "download_count": 133300, "rating": "4.5"},
    {"skill_id": "xdrop", "name": "XDrop", "description": "Cloud file drop and share utility", "author": "xixu-me", "source": "github", "source_url": "https://github.com/xixu-me/skills", "category": "Tools", "tags": ["file", "share", "cloud"], "platform": "claude", "download_count": 133200, "rating": "4.3"},
    {"skill_id": "lark-im", "name": "Lark IM", "description": "Lark instant messaging operations and bot development", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Communication", "tags": ["lark", "im", "messaging", "bot"], "platform": "claude", "download_count": 133100, "rating": "4.4"},
    {"skill_id": "simple", "name": "Simple", "description": "Simplify complex code and reduce complexity", "author": "roin-orca", "source": "github", "source_url": "https://github.com/roin-orca/skills", "category": "Development", "tags": ["refactoring", "simplify", "code-quality"], "platform": "cursor", "download_count": 130200, "rating": "4.6"},
    {"skill_id": "sleek-design-mobile-apps", "name": "Sleek Design Mobile Apps", "description": "Modern mobile app design patterns and implementation", "author": "sleekdotdesign", "source": "github", "source_url": "https://github.com/sleekdotdesign/agent-skills", "category": "Design", "tags": ["mobile", "design", "app", "ios", "android"], "platform": "cursor", "download_count": 128300, "rating": "4.7"},
    {"skill_id": "azure-cost", "name": "Azure Cost Management", "description": "Monitor and optimize Azure costs", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "cost", "management", "optimization"], "platform": "claude", "download_count": 126100, "rating": "4.5"},
    {"skill_id": "soultrace", "name": "Soultrace", "description": "AI-powered code analysis and security scanning", "author": "soultrace-ai", "source": "github", "source_url": "https://github.com/soultrace-ai/soultrace-skill", "category": "Security", "tags": ["security", "analysis", "ai", "scanning"], "platform": "claude", "download_count": 119300, "rating": "4.6"},
    {"skill_id": "vercel-react-native-skills", "name": "Vercel React Native Skills", "description": "React Native development patterns for Vercel", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/agent-skills", "category": "Development", "tags": ["react-native", "mobile", "vercel"], "platform": "cursor", "download_count": 118000, "rating": "4.4"},
    {"skill_id": "improve-codebase-architecture", "name": "Improve Codebase Architecture", "description": "Refactor and improve software architecture", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Development", "tags": ["architecture", "refactoring", "design-patterns"], "platform": "claude", "download_count": 112000, "rating": "4.8"},
    {"skill_id": "seo-audit", "name": "SEO Audit", "description": "Comprehensive SEO analysis and recommendations", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["seo", "audit", "marketing", "analytics"], "platform": "claude", "download_count": 109900, "rating": "4.5"},
    {"skill_id": "tdd", "name": "Test Driven Development", "description": "TDD methodology and implementation patterns", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Development", "tags": ["tdd", "testing", "development"], "platform": "cursor", "download_count": 109300, "rating": "4.7"},
    {"skill_id": "paper-context-resolver", "name": "Paper Context Resolver", "description": "Resolve academic paper context and references for AI", "author": "lllllllama", "source": "github", "source_url": "https://github.com/lllllllama/ai-paper-reproduction-skill", "category": "Research", "tags": ["papers", "research", "academic", "context"], "platform": "claude", "download_count": 108500, "rating": "4.6"},
    {"skill_id": "lark-approval", "name": "Lark Approval", "description": "Lark approval workflow automation", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "approval", "workflow", "automation"], "platform": "claude", "download_count": 105700, "rating": "4.4"},
    {"skill_id": "pdf", "name": "PDF Processing", "description": "Read, create, and manipulate PDF documents", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Document", "tags": ["pdf", "document", "processing"], "platform": "claude", "download_count": 105400, "rating": "4.5"},
    {"skill_id": "pptx", "name": "PowerPoint Processing", "description": "Create and edit PowerPoint presentations programmatically", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Document", "tags": ["powerpoint", "presentation", "document"], "platform": "claude", "download_count": 104400, "rating": "4.4"},
    {"skill_id": "copywriting", "name": "Copywriting", "description": "AI-powered copywriting for marketing and ads", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["copywriting", "marketing", "content", "writing"], "platform": "claude", "download_count": 99200, "rating": "4.6"},
    {"skill_id": "using-superpowers", "name": "Using Superpowers", "description": "Get the most out of agent superpowers", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Productivity", "tags": ["superpowers", "agent", "productivity"], "platform": "claude", "download_count": 98100, "rating": "4.5"},
    {"skill_id": "azure-observability", "name": "Azure Observability", "description": "Azure Monitor, Application Insights, and logging patterns", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "monitoring", "observability", "logging"], "platform": "claude", "download_count": 98100, "rating": "4.5"},
    {"skill_id": "systematic-debugging", "name": "Systematic Debugging", "description": "Structured approach to debugging complex issues", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["debugging", "problem-solving", "methodology"], "platform": "claude", "download_count": 97400, "rating": "4.8"},
    {"skill_id": "writing-plans", "name": "Writing Plans", "description": "Create effective project plans and documentation", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Productivity", "tags": ["planning", "documentation", "writing"], "platform": "claude", "download_count": 96700, "rating": "4.6"},
    {"skill_id": "extract-design-system", "name": "Extract Design System", "description": "Extract and document design systems from existing codebases", "author": "arvindrk", "source": "github", "source_url": "https://github.com/arvindrk/extract-design-system", "category": "Design", "tags": ["design-system", "extraction", "documentation"], "platform": "cursor", "download_count": 96500, "rating": "4.7"},
    {"skill_id": "grill-with-docs", "name": "Grill With Docs", "description": "Practice technical interviews with documentation focus", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Productivity", "tags": ["interview", "documentation", "practice"], "platform": "claude", "download_count": 95200, "rating": "4.5"},
    {"skill_id": "impeccable", "name": "Impeccable", "description": "Polished, error-free writing assistance", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Writing", "tags": ["writing", "grammar", "polish", "proofreading"], "platform": "claude", "download_count": 93200, "rating": "4.8"},
    {"skill_id": "to-prd", "name": "To PRD", "description": "Convert feature requests into Product Requirements Documents", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Productivity", "tags": ["prd", "product", "documentation", "requirements"], "platform": "claude", "download_count": 91800, "rating": "4.6"},
    {"skill_id": "develop-userscripts", "name": "Develop Userscripts", "description": "Create userscripts for browser automation", "author": "xixu-me", "source": "github", "source_url": "https://github.com/xixu-me/skills", "category": "Development", "tags": ["userscript", "browser", "automation"], "platform": "cursor", "download_count": 90400, "rating": "4.3"},
    {"skill_id": "docx", "name": "Word Document Processing", "description": "Create and edit Word documents programmatically", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Document", "tags": ["word", "docx", "document", "office"], "platform": "claude", "download_count": 89900, "rating": "4.4"},
    {"skill_id": "to-issues", "name": "To Issues", "description": "Convert requirements and PRDs into GitHub issues", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Productivity", "tags": ["github", "issues", "project-management"], "platform": "claude", "download_count": 88300, "rating": "4.5"},
    {"skill_id": "next-best-practices", "name": "Next.js Best Practices", "description": "Production-ready Next.js patterns and conventions", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/next-skills", "category": "Development", "tags": ["nextjs", "react", "best-practices"], "platform": "cursor", "download_count": 86300, "rating": "4.8"},
    {"skill_id": "write-a-skill", "name": "Write a Skill", "description": "Create new AI agent skills from scratch", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Development", "tags": ["skill", "creation", "development"], "platform": "claude", "download_count": 85800, "rating": "4.7"},
    {"skill_id": "diagnose", "name": "Diagnose", "description": "Diagnose issues and suggest solutions", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Development", "tags": ["diagnosis", "debugging", "troubleshooting"], "platform": "claude", "download_count": 85700, "rating": "4.6"},
    {"skill_id": "requesting-code-review", "name": "Requesting Code Review", "description": "Effective strategies for getting valuable code reviews", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["code-review", "collaboration"], "platform": "claude", "download_count": 85600, "rating": "4.5"},
    {"skill_id": "polish", "name": "Polish", "description": "Polish code to professional standards", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Development", "tags": ["polish", "code-quality", "refactoring"], "platform": "cursor", "download_count": 85600, "rating": "4.7"},
    {"skill_id": "lark-slides", "name": "Lark Slides", "description": "Lark Slides (Feishu Slides) operations and automation", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "slides", "presentation"], "platform": "claude", "download_count": 85500, "rating": "4.4"},
    {"skill_id": "lark-attendance", "name": "Lark Attendance", "description": "Lark attendance management and reporting", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "attendance", "hr", "management"], "platform": "claude", "download_count": 84900, "rating": "4.3"},
    {"skill_id": "test-driven-development", "name": "TDD Methodology", "description": "Test-driven development best practices", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["tdd", "testing", "methodology"], "platform": "cursor", "download_count": 84700, "rating": "4.7"},
    {"skill_id": "zoom-out", "name": "Zoom Out", "description": "High-level perspective on technical decisions", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Productivity", "tags": ["thinking", "strategy", "big-picture"], "platform": "claude", "download_count": 84000, "rating": "4.6"},
    {"skill_id": "critique", "name": "Critique", "description": "Constructive code and design critique", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Development", "tags": ["critique", "review", "feedback"], "platform": "cursor", "download_count": 83000, "rating": "4.6"},
    {"skill_id": "setup-matt-pocock-skills", "name": "Setup Matt Pocock Skills", "description": "Quick setup guide for Matt Pocock's skill collection", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Development", "tags": ["setup", "installation", "skills"], "platform": "claude", "download_count": 81300, "rating": "4.4"},
    {"skill_id": "colorize", "name": "Colorize", "description": "AI-powered image colorization", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Design", "tags": ["color", "image", "ai", "design"], "platform": "cursor", "download_count": 81200, "rating": "4.5"},
    {"skill_id": "caveman-code", "name": "Caveman Code", "description": "Simplify code with caveman-style refactoring", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Development", "tags": ["refactoring", "simplify", "code-quality"], "platform": "cursor", "download_count": 80400, "rating": "4.4"},
    {"skill_id": "bolder", "name": "Bolder", "description": "Make bold design decisions confidently", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Design", "tags": ["design", "confidence", "decision-making"], "platform": "cursor", "download_count": 80400, "rating": "4.5"},
    {"skill_id": "delight", "name": "Delight", "description": "Add delightful micro-interactions to UIs", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Design", "tags": ["animation", "micro-interactions", "ui", "delight"], "platform": "cursor", "download_count": 80200, "rating": "4.6"},
    {"skill_id": "distill", "name": "Distill", "description": "Distill complex concepts into simple explanations", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Writing", "tags": ["writing", "explanation", "simplification"], "platform": "claude", "download_count": 79800, "rating": "4.7"},
    {"skill_id": "xlsx", "name": "Excel Processing", "description": "Read and write Excel spreadsheets programmatically", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Document", "tags": ["excel", "xlsx", "spreadsheet", "office"], "platform": "claude", "download_count": 79500, "rating": "4.5"},
    {"skill_id": "quieter", "name": "Quieter", "description": "Reduce code noise and improve readability", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Development", "tags": ["code-quality", "readability", "refactoring"], "platform": "cursor", "download_count": 79000, "rating": "4.5"},
    {"skill_id": "executing-plans", "name": "Executing Plans", "description": "Execute project plans effectively", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Productivity", "tags": ["planning", "execution", "project-management"], "platform": "claude", "download_count": 78500, "rating": "4.6"},
    {"skill_id": "caveman-commit", "name": "Caveman Commit", "description": "AI-powered git commit message generation", "author": "juliusbrussee", "source": "github", "source_url": "https://github.com/juliusbrussee/caveman", "category": "Development", "tags": ["git", "commit", "automation"], "platform": "cursor", "download_count": 78500, "rating": "4.4"},
    {"skill_id": "image-edit", "name": "Image Edit", "description": "AI-powered image editing and manipulation", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/runcomfy-agent-skills", "category": "Design", "tags": ["image", "ai", "editing", "manipulation"], "platform": "claude", "download_count": 78000, "rating": "4.6"},
    {"skill_id": "gpt-image-2", "name": "GPT Image 2", "description": "Generate images using GPT Image 2 model", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/agent-skills", "category": "AI", "tags": ["gpt", "image", "generation", "ai"], "platform": "claude", "download_count": 77700, "rating": "4.5"},
    {"skill_id": "flux-2-klein", "name": "Flux 2 Klein", "description": "Flux 2 model variant for artistic generation", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/runcomfy-agent-skills", "category": "AI", "tags": ["flux", "ai", "image", "artistic"], "platform": "claude", "download_count": 77600, "rating": "4.4"},
    {"skill_id": "seedance-v2", "name": "Seedance V2", "description": "High-quality video generation with Seedance", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/runcomfy-agent-skills", "category": "Media", "tags": ["video", "generation", "ai", "seedance"], "platform": "claude", "download_count": 77500, "rating": "4.5"},
    {"skill_id": "happyhorse-1-0", "name": "HappyHorse 1.0", "description": "Stable image generation model", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/runcomfy-agent-skills", "category": "AI", "tags": ["image", "generation", "stable"], "platform": "claude", "download_count": 77400, "rating": "4.3"},
    {"skill_id": "caveman-review", "name": "Caveman Review", "description": "Deep code review with improvement suggestions", "author": "juliusbrussee", "source": "github", "source_url": "https://github.com/juliusbrussee/caveman", "category": "Development", "tags": ["code-review", "ai", "improvement"], "platform": "cursor", "download_count": 77400, "rating": "4.6"},
    {"skill_id": "wan-2-7", "name": "WAN 2.7", "description": "Video generation with WAN 2.7 model", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/runcomfy-agent-skills", "category": "Media", "tags": ["video", "generation", "ai", "wan"], "platform": "claude", "download_count": 77300, "rating": "4.4"},
    {"skill_id": "caveman-compress", "name": "Caveman Compress", "description": "Intelligent code compression and optimization", "author": "juliusbrussee", "source": "github", "source_url": "https://github.com/juliusbrussee/caveman", "category": "Development", "tags": ["compression", "optimization", "code"], "platform": "cursor", "download_count": 76000, "rating": "4.3"},
    {"skill_id": "triage", "name": "Triage", "description": "Prioritize issues and tasks effectively", "author": "mattpocock", "source": "github", "source_url": "https://github.com/mattpocock/skills", "category": "Productivity", "tags": ["triage", "prioritization", "productivity"], "platform": "claude", "download_count": 75400, "rating": "4.5"},
    {"skill_id": "just-scrape", "name": "Just Scrape", "description": "Simple web scraping with Just Scrape", "author": "scrapegraphai", "source": "github", "source_url": "https://github.com/scrapegraphai/just-scrape", "category": "Data", "tags": ["scraping", "web", "data", "extraction"], "platform": "claude", "download_count": 75200, "rating": "4.5"},
    {"skill_id": "browser-use", "name": "Browser Use", "description": "AI agent browser automation and interaction", "author": "browser-use", "source": "github", "source_url": "https://github.com/browser-use/browser-use", "category": "Browser", "tags": ["browser", "automation", "ai", "agent"], "platform": "claude", "download_count": 74800, "rating": "4.7"},
    {"skill_id": "agentspace", "name": "Agentspace", "description": "Multi-agent collaboration and orchestration", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/skills", "category": "AI", "tags": ["multi-agent", "collaboration", "orchestration"], "platform": "claude", "download_count": 74400, "rating": "4.6"},
    {"skill_id": "marketing-psychology", "name": "Marketing Psychology", "description": "Psychological principles in marketing strategies", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["marketing", "psychology", "strategy"], "platform": "claude", "download_count": 72900, "rating": "4.5"},
    {"skill_id": "subagent-driven-development", "name": "Subagent Driven Development", "description": "Develop with multiple AI subagents", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["subagent", "multi-agent", "development"], "platform": "claude", "download_count": 72400, "rating": "4.7"},
    {"skill_id": "caveman-help", "name": "Caveman Help", "description": "Context-aware coding help and suggestions", "author": "juliusbrussee", "source": "github", "source_url": "https://github.com/juliusbrussee/caveman", "category": "Development", "tags": ["help", "coding", "assistance"], "platform": "cursor", "download_count": 72100, "rating": "4.4"},
    {"skill_id": "airunway-aks-setup", "name": "Airway AKS Setup", "description": "Azure AKS infrastructure setup patterns", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Cloud", "tags": ["azure", "aks", "kubernetes", "infrastructure"], "platform": "claude", "download_count": 71600, "rating": "4.4"},
    {"skill_id": "verification-before-completion", "name": "Verification Before Completion", "description": "Verify work before marking tasks complete", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Productivity", "tags": ["verification", "quality", "completeness"], "platform": "claude", "download_count": 70400, "rating": "4.6"},
    {"skill_id": "lark-okr", "name": "Lark OKR", "description": "Lark OKR tracking and management", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "okr", "management", "goals"], "platform": "claude", "download_count": 70200, "rating": "4.5"},
    {"skill_id": "supabase", "name": "Supabase Integration", "description": "Supabase backend-as-a-service integration", "author": "supabase", "source": "github", "source_url": "https://github.com/supabase/agent-skills", "category": "Database", "tags": ["supabase", "backend", "database", "auth"], "platform": "claude", "download_count": 70200, "rating": "4.7"},
    {"skill_id": "webapp-testing", "name": "Web App Testing", "description": "Comprehensive web application testing strategies", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Testing", "tags": ["testing", "web", "qa", "automation"], "platform": "claude", "download_count": 70100, "rating": "4.6"},
    {"skill_id": "content-strategy", "name": "Content Strategy", "description": "Develop effective content marketing strategies", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["content", "marketing", "strategy"], "platform": "claude", "download_count": 68200, "rating": "4.5"},
    {"skill_id": "receiving-code-review", "name": "Receiving Code Review", "description": "Handle code review feedback gracefully", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["code-review", "feedback", "collaboration"], "platform": "claude", "download_count": 67700, "rating": "4.5"},
    {"skill_id": "writing-skills", "name": "Writing Skills", "description": "Technical writing best practices for developers", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Writing", "tags": ["writing", "documentation", "technical"], "platform": "claude", "download_count": 67400, "rating": "4.7"},
    {"skill_id": "social-content", "name": "Social Content", "description": "Create engaging social media content", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["social-media", "content", "marketing"], "platform": "claude", "download_count": 67100, "rating": "4.4"},
    {"skill_id": "programmatic-seo", "name": "Programmatic SEO", "description": "Scale SEO with programmatic content generation", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["seo", "programmatic", "content", "scale"], "platform": "claude", "download_count": 66700, "rating": "4.6"},
    {"skill_id": "dispatching-parallel-agents", "name": "Dispatching Parallel Agents", "description": "Run multiple agents in parallel for efficiency", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "AI", "tags": ["multi-agent", "parallel", "efficiency"], "platform": "claude", "download_count": 65600, "rating": "4.7"},
    {"skill_id": "using-git-worktrees", "name": "Using Git Worktrees", "description": "Manage multiple git branches with worktrees", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["git", "worktree", "branching"], "platform": "cursor", "download_count": 65600, "rating": "4.5"},
    {"skill_id": "typeset", "name": "Typeset", "description": "Professional typesetting and typography", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Design", "tags": ["typography", "typeset", "design"], "platform": "cursor", "download_count": 64900, "rating": "4.6"},
    {"skill_id": "marketing-ideas", "name": "Marketing Ideas", "description": "Generate creative marketing campaign ideas", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["marketing", "ideas", "creativity"], "platform": "claude", "download_count": 64100, "rating": "4.4"},
    {"skill_id": "finishing-a-development-branch", "name": "Finishing a Development Branch", "description": "Complete development branches properly", "author": "obra", "source": "github", "source_url": "https://github.com/obra/superpowers", "category": "Development", "tags": ["git", "branch", "development", "workflow"], "platform": "claude", "download_count": 63400, "rating": "4.5"},
    {"skill_id": "overdrive", "name": "Overdrive", "description": "Maximum performance optimization techniques", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Development", "tags": ["performance", "optimization", "speed"], "platform": "cursor", "download_count": 63000, "rating": "4.6"},
    {"skill_id": "product-marketing-context", "name": "Product Marketing Context", "description": "Understand product marketing context", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["product", "marketing", "context"], "platform": "claude", "download_count": 61300, "rating": "4.4"},
    {"skill_id": "pricing-strategy", "name": "Pricing Strategy", "description": "Develop effective pricing strategies", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["pricing", "strategy", "business"], "platform": "claude", "download_count": 61300, "rating": "4.5"},
    {"skill_id": "copy-editing", "name": "Copy Editing", "description": "Professional copy editing and proofreading", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Writing", "tags": ["copy", "editing", "proofreading"], "platform": "claude", "download_count": 60300, "rating": "4.5"},
    {"skill_id": "analytics-tracking", "name": "Analytics Tracking", "description": "Implement comprehensive analytics tracking", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["analytics", "tracking", "data"], "platform": "claude", "download_count": 57900, "rating": "4.5"},
    {"skill_id": "page-cro", "name": "Page CRO", "description": "Conversion rate optimization for landing pages", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["cro", "conversion", "optimization"], "platform": "claude", "download_count": 57600, "rating": "4.6"},
    {"skill_id": "design-taste-frontend", "name": "Design Taste Frontend", "description": "Develop refined frontend design taste", "author": "leonxlnx", "source": "github", "source_url": "https://github.com/leonxlnx/taste-skill", "category": "Design", "tags": ["design", "taste", "frontend", "aesthetic"], "platform": "cursor", "download_count": 57000, "rating": "4.7"},
    {"skill_id": "launch-strategy", "name": "Launch Strategy", "description": "Plan successful product launches", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["launch", "strategy", "product"], "platform": "claude", "download_count": 56200, "rating": "4.6"},
    {"skill_id": "schema-markup", "name": "Schema Markup", "description": "Implement schema.org structured data", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["seo", "schema", "structured-data"], "platform": "claude", "download_count": 55600, "rating": "4.4"},
    {"skill_id": "email-sequence", "name": "Email Sequence", "description": "Create effective email marketing sequences", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["email", "marketing", "automation", "sequence"], "platform": "claude", "download_count": 55300, "rating": "4.5"},
    {"skill_id": "firecrawl", "name": "Firecrawl", "description": "Advanced web crawling and data extraction", "author": "firecrawl", "source": "github", "source_url": "https://github.com/firecrawl/cli", "category": "Data", "tags": ["crawling", "scraping", "data", "extraction"], "platform": "claude", "download_count": 54900, "rating": "4.6"},
    {"skill_id": "paid-ads", "name": "Paid Ads", "description": "Create and optimize paid advertising campaigns", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["ads", "advertising", "paid", "campaigns"], "platform": "claude", "download_count": 54800, "rating": "4.4"},
    {"skill_id": "normalize", "name": "Normalize", "description": "Standardize and normalize data formats", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Data", "tags": ["normalization", "data", "standardization"], "platform": "claude", "download_count": 54600, "rating": "4.4"},
    {"skill_id": "mcp-builder", "name": "MCP Builder", "description": "Build Model Context Protocol integrations", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Development", "tags": ["mcp", "protocol", "integration", "ai"], "platform": "claude", "download_count": 54400, "rating": "4.7"},
    {"skill_id": "firebase-basics", "name": "Firebase Basics", "description": "Firebase fundamentals and common patterns", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "Backend", "tags": ["firebase", "backend", "google", "database"], "platform": "claude", "download_count": 54400, "rating": "4.6"},
    {"skill_id": "canvas-design", "name": "Canvas Design", "description": "Design with HTML5 Canvas API", "author": "anthropics", "source": "github", "source_url": "https://github.com/anthropics/skills", "category": "Design", "tags": ["canvas", "graphics", "design", "html5"], "platform": "cursor", "download_count": 54300, "rating": "4.5"},
    {"skill_id": "competitor-alternatives", "name": "Competitor Alternatives", "description": "Research and present competitor alternatives", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["competitors", "alternatives", "research"], "platform": "claude", "download_count": 54300, "rating": "4.3"},
    {"skill_id": "kling-3-0", "name": "Kling 3.0", "description": "Video generation with Kling 3.0 model", "author": "agentspace-so", "source": "github", "source_url": "https://github.com/agentspace-so/runcomfy-agent-skills", "category": "Media", "tags": ["video", "generation", "ai", "kling"], "platform": "claude", "download_count": 54100, "rating": "4.5"},
    {"skill_id": "firebase-auth-basics", "name": "Firebase Auth Basics", "description": "Firebase Authentication patterns", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "Backend", "tags": ["firebase", "auth", "authentication", "security"], "platform": "claude", "download_count": 53900, "rating": "4.5"},
    {"skill_id": "onboarding-cro", "name": "Onboarding CRO", "description": "Optimize user onboarding conversion rates", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["onboarding", "cro", "conversion", "ux"], "platform": "claude", "download_count": 53800, "rating": "4.5"},
    {"skill_id": "extract", "name": "Extract", "description": "Extract structured data from unstructured text", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Data", "tags": ["extraction", "data", "nlp"], "platform": "claude", "download_count": 53500, "rating": "4.6"},
    {"skill_id": "frontend-polish", "name": "Frontend Polish", "description": "Polish frontend code to perfection", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Development", "tags": ["frontend", "polish", "code-quality"], "platform": "cursor", "download_count": 53500, "rating": "4.7"},
    {"skill_id": "ai-seo", "name": "AI SEO", "description": "AI-powered SEO optimization", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["seo", "ai", "optimization"], "platform": "claude", "download_count": 53400, "rating": "4.5"},
    {"skill_id": "onboard", "name": "Onboard", "description": "Smooth user onboarding experiences", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Productivity", "tags": ["onboarding", "ux", "user-experience"], "platform": "cursor", "download_count": 53400, "rating": "4.6"},
    {"skill_id": "harden", "name": "Harden", "description": "Harden code security and best practices", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Security", "tags": ["security", "hardening", "best-practices"], "platform": "claude", "download_count": 53300, "rating": "4.7"},
    {"skill_id": "form-cro", "name": "Form CRO", "description": "Optimize form conversion rates", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["forms", "cro", "conversion", "optimization"], "platform": "claude", "download_count": 52700, "rating": "4.4"},
    {"skill_id": "firebase-hosting-basics", "name": "Firebase Hosting Basics", "description": "Deploy to Firebase Hosting", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "Backend", "tags": ["firebase", "hosting", "deployment"], "platform": "claude", "download_count": 52600, "rating": "4.4"},
    {"skill_id": "free-tool-strategy", "name": "Free Tool Strategy", "description": "Leverage free tools in marketing", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["free", "tools", "marketing", "strategy"], "platform": "claude", "download_count": 52500, "rating": "4.3"},
    {"skill_id": "referral-program", "name": "Referral Program", "description": "Design and implement referral programs", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["referral", "marketing", "growth"], "platform": "claude", "download_count": 52400, "rating": "4.5"},
    {"skill_id": "firebase-app-hosting-basics", "name": "Firebase App Hosting Basics", "description": "Firebase App Hosting deployment", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "Backend", "tags": ["firebase", "hosting", "app", "deployment"], "platform": "claude", "download_count": 52300, "rating": "4.4"},
    {"skill_id": "ab-test-setup", "name": "A/B Test Setup", "description": "Set up proper A/B tests", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["a-b-test", "testing", "optimization"], "platform": "claude", "download_count": 52200, "rating": "4.6"},
    {"skill_id": "firebase-data-connect", "name": "Firebase Data Connect", "description": "Firebase Data Connect GraphQL integration", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "Backend", "tags": ["firebase", "graphql", "data", "connect"], "platform": "claude", "download_count": 52000, "rating": "4.5"},
    {"skill_id": "signup-flow-cro", "name": "Signup Flow CRO", "description": "Optimize signup flow conversion", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["signup", "cro", "conversion", "funnel"], "platform": "claude", "download_count": 52000, "rating": "4.4"},
    {"skill_id": "paywall-upgrade-cro", "name": "Paywall Upgrade CRO", "description": "Optimize paywall and upgrade flows", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["paywall", "upgrade", "cro", "subscription"], "platform": "claude", "download_count": 51600, "rating": "4.5"},
    {"skill_id": "popup-cro", "name": "Popup CRO", "description": "Convert more with strategic popups", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["popup", "cro", "conversion", "marketing"], "platform": "claude", "download_count": 51200, "rating": "4.3"},
    {"skill_id": "deploy-to-vercel", "name": "Deploy to Vercel", "description": "One-click deployment to Vercel", "author": "vercel-labs", "source": "github", "source_url": "https://github.com/vercel-labs/agent-skills", "category": "DevOps", "tags": ["vercel", "deploy", "hosting"], "platform": "cursor", "download_count": 51200, "rating": "4.6"},
    {"skill_id": "developing-genkit-js", "name": "Developing Genkit JS", "description": "Build AI apps with Google Genkit for JS", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "AI", "tags": ["genkit", "ai", "google", "javascript"], "platform": "claude", "download_count": 50900, "rating": "4.6"},
    {"skill_id": "developing-genkit-dart", "name": "Developing Genkit Dart", "description": "Build AI apps with Google Genkit for Dart", "author": "firebase", "source": "github", "source_url": "https://github.com/firebase/agent-skills", "category": "AI", "tags": ["genkit", "ai", "google", "dart"], "platform": "claude", "download_count": 50700, "rating": "4.5"},
    {"skill_id": "audit-website", "name": "Audit Website", "description": "Comprehensive website auditing", "author": "squirrelscan", "source": "github", "source_url": "https://github.com/squirrelscan/skills", "category": "Security", "tags": ["audit", "security", "website", "analysis"], "platform": "claude", "download_count": 50500, "rating": "4.6"},
    {"skill_id": "teach-impeccable", "name": "Teach Impeccable", "description": "Learn to use the Impeccable skill system", "author": "pbakaus", "source": "github", "source_url": "https://github.com/pbakaus/impeccable", "category": "Productivity", "tags": ["learning", "impeccable", "training"], "platform": "claude", "download_count": 50300, "rating": "4.4"},
    {"skill_id": "better-auth-best-practices", "name": "Better Auth Best Practices", "description": "Authentication best practices with Better Auth", "author": "better-auth", "source": "github", "source_url": "https://github.com/better-auth/skills", "category": "Security", "tags": ["auth", "authentication", "security", "best-practices"], "platform": "claude", "download_count": 50200, "rating": "4.7"},
    {"skill_id": "high-end-visual-design", "name": "High-End Visual Design", "description": "Create high-end visual designs", "author": "leonxlnx", "source": "github", "source_url": "https://github.com/leonxlnx/taste-skill", "category": "Design", "tags": ["design", "visual", "high-end", "aesthetic"], "platform": "cursor", "download_count": 50100, "rating": "4.8"},
    {"skill_id": "redesign-existing-projects", "name": "Redesign Existing Projects", "description": "Redesign and refresh existing projects", "author": "leonxlnx", "source": "github", "source_url": "https://github.com/leonxlnx/taste-skill", "category": "Design", "tags": ["redesign", "refresh", "ui", "projects"], "platform": "cursor", "download_count": 49100, "rating": "4.6"},
    {"skill_id": "ad-creative", "name": "Ad Creative", "description": "Create compelling ad creatives", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["ads", "creative", "advertising"], "platform": "claude", "download_count": 48500, "rating": "4.4"},
    {"skill_id": "lark-markdown", "name": "Lark Markdown", "description": "Lark Markdown syntax and conversion", "author": "larksuite", "source": "github", "source_url": "https://github.com/larksuite/cli", "category": "Productivity", "tags": ["lark", "markdown", "document"], "platform": "claude", "download_count": 48400, "rating": "4.3"},
    {"skill_id": "cold-email", "name": "Cold Email", "description": "Write effective cold emails", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["email", "cold-email", "outreach"], "platform": "claude", "download_count": 48300, "rating": "4.4"},
    {"skill_id": "emil-design-eng", "name": "Emil Design Engineering", "description": "Design engineering practices", "author": "emilkowalski", "source": "github", "source_url": "https://github.com/emilkowalski/skill", "category": "Design", "tags": ["design", "engineering", "frontend"], "platform": "cursor", "download_count": 47400, "rating": "4.7"},
    {"skill_id": "convex-quickstart", "name": "Convex Quickstart", "description": "Get started with Convex backend", "author": "get-convex", "source": "github", "source_url": "https://github.com/get-convex/agent-skills", "category": "Backend", "tags": ["convex", "backend", "database", "realtime"], "platform": "claude", "download_count": 47200, "rating": "4.6"},
    {"skill_id": "sentry-cli", "name": "Sentry CLI", "description": "Sentry error tracking and monitoring", "author": "sentry", "source": "github", "source_url": "https://github.com/sentry/dev", "category": "DevOps", "tags": ["sentry", "monitoring", "errors", "tracking"], "platform": "claude", "download_count": 46700, "rating": "4.5"},
    {"skill_id": "convex-performance-audit", "name": "Convex Performance Audit", "description": "Audit Convex backend performance", "author": "get-convex", "source": "github", "source_url": "https://github.com/get-convex/agent-skills", "category": "Backend", "tags": ["convex", "performance", "audit", "optimization"], "platform": "claude", "download_count": 46700, "rating": "4.5"},
    {"skill_id": "entra-agent-id", "name": "Entra Agent ID", "description": "Microsoft Entra ID agent authentication", "author": "microsoft", "source": "github", "source_url": "https://github.com/microsoft/azure-skills", "category": "Security", "tags": ["entra", "azure-ad", "authentication", "identity"], "platform": "claude", "download_count": 46300, "rating": "4.4"},
    {"skill_id": "churn-prevention", "name": "Churn Prevention", "description": "Strategies to prevent customer churn", "author": "coreyhaines31", "source": "github", "source_url": "https://github.com/coreyhaines31/marketingskills", "category": "Marketing", "tags": ["churn", "retention", "customer"], "platform": "claude", "download_count": 46000, "rating": "4.5"},
    {"skill_id": "compress", "name": "Compress", "description": "Smart code compression utilities", "author": "juliusbrussee", "source": "github", "source_url": "https://github.com/juliusbrussee/caveman", "category": "Development", "tags": ["compress", "optimization", "code"], "platform": "cursor", "download_count": 45900, "rating": "4.3"},
]


CATEGORIES = ["Development", "Design", "Marketing", "Cloud", "AI", "Database", "Security", "DevOps", "Productivity", "Tools", "UI Components", "Media", "Document", "Communication", "Writing", "Testing", "Browser", "Data", "Research", "Backend"]


def populate_skills():
    Base.metadata.create_all(sync_engine)

    db = get_sync_db()

    existing = db.query(Skill).count()
    if existing > 0:
        print(f"Database already has {existing} skills. Skipping...")
        return

    for i, data in enumerate(SKILLS_DATA):
        version = data.get("version", "main")
        skill_id = generate_skill_id(data["source_url"], data["name"], version)
        skill_name_slug = data["name"].lower().replace(' ', '-')
        content = fetch_skill_content(data["source_url"], skill_name_slug, version)
        skill = Skill(
            id=uuid.uuid4(),
            skill_id=skill_id,
            name=data["name"],
            description=data["description"],
            version=version,
            commit_id=data.get("commit_id"),
            author=data["author"],
            source=data["source"],
            source_url=data["source_url"],
            category=data.get("category", random.choice(CATEGORIES)),
            tags=data["tags"],
            platform=data.get("platform", "claude"),
            extra_metadata={},
            content=content,
            security_score=random.randint(70, 100),
            download_count=data.get("download_count", random.randint(1000, 100000)),
            rating=data.get("rating", f"{random.uniform(4.0, 5.0):.1f}"),
            created_at=datetime.utcnow() - timedelta(days=random.randint(1, 365)),
            updated_at=datetime.utcnow(),
        )
        db.add(skill)

        if (i + 1) % 50 == 0:
            db.commit()
            print(f"Inserted {i + 1} skills...")

    db.commit()
    total = db.query(Skill).count()
    print(f"Successfully inserted {total} skills!")
    db.close()


if __name__ == "__main__":
    populate_skills()